# Generated by Django 4.2.7 on 2023-12-31 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='client',
            field=models.CharField(max_length=300, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='commants',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='contact',
            field=models.CharField(max_length=500, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='id_employee',
            field=models.ManyToManyField(related_name='project_employee_user', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='id_project_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_pm_user', to=settings.AUTH_USER_MODEL, verbose_name='Project manager'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='number',
            field=models.IntegerField(verbose_name='Project number1'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='number_2',
            field=models.IntegerField(verbose_name='Project number2'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_type',
            field=models.CharField(max_length=50, verbose_name='Project type'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
