# Generated by Django 4.2.7 on 2024-01-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_rename_number_projectmodel_number_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='number_1',
            new_name='number1',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='number_2',
            new_name='number2',
        ),
    ]
