# Generated by Django 4.2.7 on 2024-01-01 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0004_rename_number_1_projectmodel_number1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='id_project_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_pm_user', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
    ]
