# Generated by Django 4.2.7 on 2023-12-31 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is completed')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Whether approved')),
                ('approver_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='holiday_approver_user', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='holiday_user', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
        ),
    ]
