# Generated by Django 4.2.7 on 2023-12-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='adhar_number',
            new_name='adhar',
        ),
    ]
