# Generated by Django 4.2.7 on 2024-01-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofileinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_state',
            field=models.ForeignKey(choices=[('Present', 'Present'), ('Absent', 'Absent')], null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_state', to='accounts.userstatemodel', verbose_name='User status'),
        ),
    ]
