# Generated by Django 4.2.7 on 2024-01-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofileinfo_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_work_hours',
            field=models.ForeignKey(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_work_hours', to='accounts.workhoursmodel', verbose_name='Work hours'),
        ),
    ]
