# Generated by Django 4.2.7 on 2024-01-02 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofileinfo_user_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhoursmodel',
            name='work_hour',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_work_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_work_hours', to='accounts.workhoursmodel', verbose_name='Work hours'),
        ),
        migrations.AlterField(
            model_name='workhoursmodel',
            name='rate_of_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Pay rate'),
        ),
    ]
